name: Security Analysis

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  security:
    name: Security Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: oxc-project/security-action@57ad85d07dae1ebcb2ddc237ee89e0c68eaf8c5d # v0.0.4
